### PR TITLE
Support both global and local style?

### PR DESCRIPTION
**Pull request by thedv91**
Follow:
[https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet](https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet)

### CODE REVIEW

**Comment by chacbumbum** [comment]
I think our project needs both global style and local style.
Can make more flexible?

**Comment by felixmosh** [comment]
It can be simplified by using the [`oneOf`](https://webpack.js.org/configuration/module/#ruleoneof) webpack feature.

I've managed to change the config from outside by using this in `next.config.js` file:

```
config.module.rules.forEach(rule => {
  if (rule.test.toString().includes('.scss')) {
    rule.rules = rule.use.map(useRule => {
      if (typeof useRule === 'string') {
        return {
          loader: useRule,
        };
      }
      if (useRule.loader.startsWith('css-loader')) {
        return {
          oneOf: [
            {
              test: /\.global\.scss$/,
              loader: useRule.loader,
              options: {
                ...useRule.options,
                modules: false,
              },
            },
            {
              loader: useRule.loader,
              options: useRule.options,
            },
          ],
        };
      }

      return useRule;
    });

    delete rule.use;
  }
});
```

**Comment by thedv91** [comment]
@felixmosh yep I think we can customize `next.config.js` but I want to support options from packages

**Comment by jlmakes** [comment]
Damn @felixmosh that should be a part of the docs.

**Comment by felixmosh** [comment]
I want it to be part of next-scss/css :)

**Comment by bez4pieci** [comment]
Please add this, it is super useful during migration to CSS Components.

**Comment by icewheel** [comment]
this is the missing feature that will be very helpful.

**Comment by timneutkens** [comment]
I'm going to close this in favor of https://github.com/zeit/next.js/issues/8626

Thanks for your contribution 🙏

**Comment by warriv93** [comment]
Great work, thank you!

**Pull request closed without merging**
