### PR TITLE
Add extracted-loader

### LINKED ISSUE #25: next-css Production Example
The example in [this documentation](https://github.com/zeit/next-plugins/tree/master/packages/next-css#production-usage) points out to statically `<link>` to the statically generated CSS file. However, when doing so this will also apply to dev environments, where this link may be 404 or has outdated CSS styles. Please demonstrate an example that only uses this static file reference for production.

### PR DESCRIPTION
**Pull request by timneutkens**
Fixes #25, #20 
:wave: FOUC when using next-css.

This adds https://github.com/sheerun/extracted-loader which works on the extracted stylesheet.

Thanks @sheerun for the loader :pray:

### CODE REVIEW

**Comment by timneutkens** [comment]
Will have to reflect this onto next-sass and next-less too.

**Comment by huangbong** [comment]
Great work @timneutkens! 👏

**Comment by sheerun** [comment]
You're welcome. As a reward I choose merging of https://github.com/zeit/next.js/pull/3451

**Comment by sheerun** [comment]
btw. I've released version 1.0.6 that fixes some issues

**Pull request merged**
