### PR TITLE
Bumped webpack bundle analyzer dependency

### PR DESCRIPTION
**Pull request by wallynm**
Fixed npm audit error related with cross scripting

image

### CODE REVIEW

**Comment by timneutkens** [comment]
https://github.com/zeit/next-plugins/tree/master/packages/next-bundle-analyzer#nextjs--webpack-bundle-analyzer

This plugin was moved into the Next.js repo

**Comment by wallynm** [comment]
Se should update some Readme with this info, só people would know about this...

When someone get's here, how he could know the right place to use this plugin?

**Comment by wallynm** [comment]
But i didnt understood the link you send, it's refering tô this same repository.

**Comment by timneutkens** [comment]
It has a message in the readme:

> 📢 This repo is now deprecated and has been moved to @next/bundle-analyzer

**Pull request closed without merging**
