### PR TITLE
Updated next-css to work with latest css-loader package

### PR DESCRIPTION
**Pull request by dementeddevil**
Updated packages version and tweaked loader configuration to deal with latest css-loader

### CODE REVIEW

**Comment by zyrepo** [comment]
When will this be released

**Comment by loan-laux** [comment]
I know it's not very constructive, but +1 on this. Would love to see it merged.

**Comment by timneutkens** [comment]
I'm going to close this in favor of https://github.com/zeit/next.js/issues/8626

**Comment by evocateur** [comment]
@timneutkens In the meantime, users of any of these plugins that attempt to upgrade to `next@9.0.7` will be broken?

```
Creating an optimized production build

Failed to compile.

./pages/admin/styles.less
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'exportOnlyLocals'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals? }

> Build error occurred
Error: > Build failed because of webpack errors
```

**Comment by fabinppk** [comment]
My next is in 9.0.7 version and using `css-loader@3.2.0`, but `@zeit/next-css@1.0.1` is in css-loader@1.0.0.

I not have a good solution yet. :thinking: :cry:

**Pull request closed without merging**
