### PR TITLE
Allow for extra stylesheet loaders

### PR DESCRIPTION
**Pull request by sheerun**

### CODE REVIEW

**Comment by dayze** [comment]
Bump, I need it to

**Comment by Tykrael** [comment]
Truly needed

**Comment by jeremy-habit** [comment]
Useful

**Comment by sheerun** [comment]
Why you marked it as wip? Please merge..

**Comment by timneutkens** [comment]
I'm going to close this in favor of https://github.com/zeit/next.js/issues/8626

Thanks for your contribution 🙏

**Pull request closed without merging**
