### PR TITLE
feat: add @zeit/next-bundle-analyzer

### PR DESCRIPTION
**Pull request by jimthedev**
Analyze both your front end bundle and back end bundle with webpack-bundle-analyzer in next.js

### CODE REVIEW

**Comment by jimthedev** [comment]
A Gif of it in action

bundle-analyzer

**Comment by jimthedev** [comment]
@timneutkens Rebased w/latest.

**Comment by timneutkens** [comment]
@jimthedev cleaned up the code, it did a lot it didn't have to do 👍If you could review my changes I'll merge after 👍

**Comment by jimthedev** [comment]
@timneutkens Awesome. Reviewed. LGTM.

**Pull request merged**
