### PR TITLE
add next-css option to disable auto-adding postcss-loader

### PR DESCRIPTION
**Pull request by gavinsharp**
I have a situation where I would like to run postcss from one of my custom webpack loaders, but don't want the Next.js CSS loader to invoke postcss. Right now, the Next.js CSS loader automatically adds the postcss loader if a `postcss.config.js` file is found.

This adds support for a `autoAddPostcss` option (defaulting to true, i.e. existing behavior), which can be set to false to avoid the "automatically add postcss loader" behaviour.

### CODE REVIEW

**Comment by radeno** [comment]
@gavinsharp maybe just idea about argument naming. `usePostcss` or `withPostcss` sounds for me more clear.

**Comment by gavinsharp** [comment]
> @gavinsharp maybe just idea about argument naming. `usePostcss` or `withPostcss` sounds for me more clear.

I do like those names better, but my concern was that those simpler names kind of obfuscate the magic behavior that is conditional on presence of the config file. E.g. you might wonder why postCSS isn't running when you pass `withPostcss: true` but don't have a config file present. I am not a fan of the magic personally, and would prefer requiring explicit configuration, but I know that can be a touchy difference of opinion :)

**Comment by gavinsharp** [comment]
My workaround for this issue, by the way, was to use a `.postcssrc.js` instead of `postcss.config.js` - postcss loads it fine, but `next-css` doesn't look for it.

**Comment by radeno** [comment]
There are many ways to load postcss settings https://github.com/michael-ciniawsky/postcss-load-config#usage
so i like your workaround to enabling or disabling injecting postcss-loader. I think we could name it `injectPostcss` and it will neccessary understandable. Current behaviour is for checking `postcss.config.js` file. But it is not neccessary because postcss-loader https://github.com/postcss/postcss-loader#config-cascade do it automatically.

**Comment by timneutkens** [comment]
I'm going to close this in favor of https://github.com/zeit/next.js/issues/8626

Thanks for your contribution 🙏

**Pull request closed without merging**
