### PR TITLE
Document to use _app.js instead of _document.js

### PR DESCRIPTION
**Pull request by miukimiu**
Solves the issue #196

### CODE REVIEW

**Comment by miukimiu** [comment]
You're right! I did on the issue #196. 😛 

If you're ok with what I documented on `next-less/readme.md` I can do the same for the other ones.

**Comment by revolunet** [comment]
Wow; if this is still relevant, this should definitely be integrated in README IMHO 🙏

Ive been hit by since a few times and never realized one cannot import css into `_document.js`. One reason for the confusion is that when using styled-components, it is documented to inject the styles in document.js. Another reason is that it works in dev mode, but not in production.

**Comment by timneutkens** [comment]
It won’t work in dev mode anymore in next 7, but we should definitely clearly document this.

**Comment by revolunet** [comment]
Thanks 👍

**Pull request merged**
