### PR TITLE
Add ignoreOrder option for ExtractCssChunksPlugin

### PR DESCRIPTION
**Pull request by gwer**
This change should fix conflicting order error in ExtractCssChunksPlugin (zeit#506)

### CODE REVIEW

**Comment by uyouthe** [comment]
I mean just merge this @timneutkens

**Comment by lexwebb** [comment]
We are also struggling with this, would be great to get this merged!

**Comment by timneutkens** [comment]
I'm going to close this in favor of https://github.com/zeit/next.js/issues/8626

Thanks for your contribution 🙏

**Comment by tiffwu** [comment]
@timneutkens Any way this could go in as a stopgap? Not sure what the timeline looks like for https://github.com/zeit/next.js/issues/8626.

**Comment by adFedorovich** [comment]
still has conflicting order

**Pull request closed without merging**
