### PR TITLE
Adding next-workers plugin to support Web Workers

### PR DESCRIPTION
**Pull request by bendman**
This makes it easier to implement Web Workers, as per [this issue](https://github.com/zeit/next.js/issues/4768).

### CODE REVIEW

**Comment by philcockfield** [comment]
This looks great.  When do you reckon they'll merge?

**Comment by philcockfield** [comment]
Thanks @timneutkens.  And thanks @bendman for the PR.  I love how most things I'm looking for are already accounted for the smart folks circling the Zeit ecosystem.

**Comment by philcockfield** [comment]
@timneutkens - was the process from here to having this published to NPM?

**Comment by bendman** [comment]
@philcockfield @timneutkens Same question. Should/can I publish this to NPM myself, or is that something done through a zeit NPM account?

**Comment by timneutkens** [comment]
It's published already as a canary version.

**Comment by timneutkens** [comment]
https://www.npmjs.com/package/@zeit/next-workers

**Comment by philcockfield** [comment]
https://spectrum.chat/thread/c847d538-8a9e-412c-a625-e6b99344db34

This all of a sudden has stopped working for me.  Possibly when jumping to `Next@7`.

@bendman, is this working for you OK on `Next@7` still?

**Comment by philcockfield** [comment]
Awesome - thanks @bendman

**Pull request merged**
