### PR TITLE
Add link to next-pino

### PR DESCRIPTION
**Pull request by khaeransori**

### CODE REVIEW

**Comment by alexindigo** [comment]
Interesting plugin. It's very similar to our use case.
And for us it looks like webpack was able to fetch browser version from pino,
without extra steps. Wondering what is your use case here. Thank you.

**Comment by timneutkens** [comment]
> Wondering what is your use case here.

Same thought here, but I'll add it to the list 😄

**Comment by alexindigo** [comment]
My concern that it would make next-pino look like “blessed” way of doing things. Which seems going against the grain of next, making things simple and keeping it “natural”.

**Comment by khaeransori** [comment]
Hi @alexindigo @timneutkens 

This is used for my internal project, I'm in the middle of partially migrating it to next.js, and somehow webpack can't resolve browser field on package.json, therefore I must aliasing pino into its own browser version.
After some thought maybe I should not create this package public, since only me whose using it.

wdyt ?

**Comment by alexindigo** [comment]
@khaeransori There is nothing wrong with publishing modules, it's awesome. And if you can publish things, you definitely should. :)
As for this specific one, it sounds like it might be issue with your webpack config.
What version of webpack you're using?

And what could be useful with in plugin, is ability to provide different instances (with different configs) for the client side and for the server side.

**Pull request merged**
