### PR TITLE
Add typescripts baseUrl setting to webpacks module resolver

### PR DESCRIPTION
**Pull request by cyrilwanner**
### `@zeit/next-typescript`
When taking advantage of TypeScripts `baseUrl` setting to get rid of these long relative imports, you'll currently get an error because only typescript knows about it but webpack/babel doesn't know how to resolve the path.

The changes in this PR fix this by adding the `baseUrl` of the `tsconfig.json` to webpacks [`resolve.modules`](https://webpack.js.org/configuration/resolve/#resolve-modules) setting so the paths get resolved exactly the same.

As the [usage instructions in @zeit/next-typescripts readme](https://github.com/zeit/next-plugins/blob/master/packages/next-typescript/readme.md#usage) also suggest setting the `baseUrl` setting, I think this should be the default behavior (editors also autoimport with this value).

There is no additional configuration needed.

```typescript
// pages/user/settings/privacy/index.js

// without baseUrl:
import Button from '../../../../components/Button';

// with baseUrl set to . as in the usage instruction in the readme:
import Button from 'components/Button';
```

### CODE REVIEW

**Comment by kachkaev** [comment]
I'm not a person who decides here, but I'd still like to say that I'm not a fan of local imports with paths like `'components/Button'`. This way it's too easy to forget if a resource is from an npm module or from a local source directory and a bit of extra brain power is needed to figure that out. IMO There's nothing wrong in `../../` in paths to local modules as these are easy to _search and replace_, should any major refactoring occur.

If a developer has to manually fiddle with `../` too often, this may be a sing of an issue in the project structure, not a problem with `../` per se.

**Comment by cyrilwanner** [comment]
@kachkaev Yes this might have to do something with the project structure. However, I think it is a matter of opinion which version is better/cleaner. I find it easier to read imports and see from where they are coming like this because I don't have to walk up the folder structure one by one. In a bigger project with many components and pages, you sometimes can't really avoid `../../../../` and so I find it easier if I see the import from the root folder of my project (or that defined in `baseUrl`).

But this change doesn't force you to write imports like this, you can still write them like before. It only makes the plugin compatible with the `baseUrl` setting if someone _wants_ to use imports like this. Everyone should be free to decide which version they want to use, but I think it should be possible to use both version, specially when TypeScript supports this out of the box and also `@zeit/next-typescript` has this value set in their usage instructions (even before this PR).

**Comment by kachkaev** [comment]
The problem with adding `baseUrl` to the plugin may create a situation when someone commits `'components/Button'` when other of project contributors are against this and there will be no way to, say, fail a CI based on that.

About two years ago when I was playing with early ES6 modules in meteor, it was possible to write `import X from '/components/Button'` (i.e. with a ‘root’ slash in the beginning). Is it something that's still supported anywhere? The good thing about `/` is that it helps distinguish between local modules and those in `node_modules` directory.

**Comment by cyrilwanner** [comment]
Well, if you don't want these imports in your project, you can simply omit the `baseUrl` setting for typescript. Editors then don't auto import with these paths anymore and CI will fail. The plugin will only propagate `baseUrl` to webpack if it is explicitly set in `tsconfig.json` and so someone really wants it.

I think it is not possible to import it with a leading slash out of the box. It might be possible with some other settings in the `tsconfig.json` but I'm not sure, I did not see that in the TypeScript world so far.

I understand your concerns and they are totally valid. I just think that everyone looks differently at this "problem" and if someone explicitly wants to set and use the `baseUrl` feature which TypeScript provides out of the box, this plugin should be able to handle it. But I think it is up to Zeit to decide if they want this feature in their official TypeScript plugin. They should now have pros and cons from both sides :)

**Comment by kachkaev** [comment]
> The plugin will only propagate `baseUrl` to webpack if it is explicitly set in tsconfig.json and so someone really wants it.

LGTM then!

**Comment by djskinner** [comment]
Also needed for monorepos :+1:

**Comment by djskinner** [comment]
Perhaps this can be better achieved using `tsconfig-paths-webpack-plugin`?

```        config.resolve.plugins = [
            new TsconfigPathsPlugin({ configFile: path.join(__dirname, "./tsconfig.json") })
        ]

**Comment by mehmetnyarar** [comment]
I've managed to solve this with `tsconfig-paths-webpack-plugin`, thanks to @djskinner :

In the component

`import { Layout } from '@components/Layout'`

In `tsconfig.json`

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@components/*": [
        "components/*"
      ]
    }
  }
}
```

In `next.config.js`

```js
const withTypescript = require('@zeit/next-typescript')
const withSass = require('@zeit/next-sass')
const withPlugins = require('next-compose-plugins')
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin')

const nextConfig = {
  webpack: (config, options) => {
    config.resolve.plugins = [
      new TsconfigPathsPlugin({
        configFile: path.join(__dirname, "./tsconfig.json")
      })
    ]
    return config;
  },
};

module.exports = withPlugins([
  [withSass({
    cssModules: true
  })],
  [withTypescript]
], nextConfig)
```

**Comment by mehmetnyarar** [comment]
nope. strangely, `pages/index.tsx` is resolved, but other pages don't resolve...

**Comment by mehmetnyarar** [comment]
I'd like to import my components like this:

`import { Layout } from '@components/Layout'`

I've tried the following configurations, but it didn't work. Is there any solution to this?

In `tsconfig.json`

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@components/*": [
        "components/*"
      ]
    }
  }
}
```

In `next.config.js`

```js
const withTypescript = require('@zeit/next-typescript')
const withSass = require('@zeit/next-sass')
const withPlugins = require('next-compose-plugins')
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin')

const nextConfig = {
  webpack: (config, options) => {
    config.resolve.plugins = [
      new TsconfigPathsPlugin({
        configFile: path.join(__dirname, "./tsconfig.json")
      })
    ]
    return config;
  },
};

module.exports = withPlugins([
  [withSass({
    cssModules: true
  })],
  [withTypescript]
], nextConfig)
```

```json
{
  "dependencies": {
    "next": "^8.1.0",
    "node-sass": "^4.12.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "@types/next": "^8.0.4",
    "@types/react": "^16.8.14",
    "@types/react-dom": "^16.8.4",
    "@types/styled-jsx": "^2.2.8",
    "@typescript-eslint/eslint-plugin": "^1.7.0",
    "@typescript-eslint/parser": "^1.7.0",
    "@zeit/next-sass": "^1.0.1",
    "@zeit/next-typescript": "^1.1.1",
    "next-compose-plugins": "^2.2.0",
    "standard": "^12.0.1",
    "tsconfig-paths-webpack-plugin": "^3.2.0",
    "tslint": "^5.16.0",
    "tslint-config-standard": "^8.0.1"
  },
}
```

**Comment by timneutkens** [comment]
I'm going to close this as the TypeScript plugin is now an empty shell.

**Pull request closed without merging**
