### PR TITLE
Upgraded webpack-bundle-analyzer version due to a moderate security issue

### PR DESCRIPTION
**Pull request by Frai**

### CODE REVIEW

**Comment by timneutkens** [comment]
Actually this package is deprecated and moved to https://github.com/zeit/next.js/tree/canary/packages/next-bundle-analyzer

So maybe there should be a note + link to the new repo.

**Comment by Frai** [comment]
@timneutkens I apologise but I didn't understand your comment (and I've been reading it for the past hour). A note and a link to the new repo? You mean that I should change the base from `zeit:master` to `zeit:canary` perhaps? I'm sorry if I misunderstood you.

**Comment by timneutkens** [comment]
This plugin, which is `@zeit/next-bundle-analyzer` was moved into the Next.js monorepo: https://github.com/zeit/next.js/tree/canary/packages/next-bundle-analyzer

It's now called `@next/bundle-analyzer` and that's the one everyone should use from now on.

**Comment by Frai** [comment]
I see, thank you for the explanation @timneutkens.

**Pull request closed without merging**
