### PR TITLE
Allow for postcss-loader options to be passed

### PR DESCRIPTION
**Pull request by ashwinibm**
Make it possible to pass postcss-loader options like config (path, context), parser, etc.
This can be useful, for example, to pass theme env variables to postcss-loader.

next.config.js would look like:
```
module.exports = withCSS({
  postcssLoaderOptions: {
    parser: true,
    config: {
      ctx: {
        theme: JSON.stringify(process.env.REACT_APP_THEME)
      }
    }
  }
})
```

### CODE REVIEW

**Comment by ashwinibm** [comment]
@timneutkens I have updated as per your comments.

**Comment by ashwinibm** [comment]
@timneutkens I rebased my branch to master since next-stylus was newly added. How do you suggest I fix it? Sorry, I'm a little new to this.

**Comment by timneutkens** [comment]
I'd create a new branches based on origin/master and copy over the changes you made 👍

**Comment by ashwinibm** [comment]
@timneutkens Cool, I've done that. Here's the new PR: https://github.com/zeit/next-plugins/pull/201

**Pull request closed without merging**
